// Code generated by protoc-gen-go. DO NOT EDIT.
// source: package.proto

package domain

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Package struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path                 string               `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Url                  string               `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Author               string               `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Data                 *PackageSnapshot     `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	FirstSeenAt          *timestamp.Timestamp `protobuf:"bytes,6,opt,name=first_seen_at,json=firstSeenAt,proto3" json:"first_seen_at,omitempty"`
	History              []*PackageCrawl      `protobuf:"bytes,7,rep,name=history,proto3" json:"history,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Package) Reset()         { *m = Package{} }
func (m *Package) String() string { return proto.CompactTextString(m) }
func (*Package) ProtoMessage()    {}
func (*Package) Descriptor() ([]byte, []int) {
	return fileDescriptor_package_efc98af9608bae55, []int{0}
}
func (m *Package) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Package.Unmarshal(m, b)
}
func (m *Package) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Package.Marshal(b, m, deterministic)
}
func (dst *Package) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Package.Merge(dst, src)
}
func (m *Package) XXX_Size() int {
	return xxx_messageInfo_Package.Size(m)
}
func (m *Package) XXX_DiscardUnknown() {
	xxx_messageInfo_Package.DiscardUnknown(m)
}

var xxx_messageInfo_Package proto.InternalMessageInfo

func (m *Package) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Package) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Package) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Package) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Package) GetData() *PackageSnapshot {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Package) GetFirstSeenAt() *timestamp.Timestamp {
	if m != nil {
		return m.FirstSeenAt
	}
	return nil
}

func (m *Package) GetHistory() []*PackageCrawl {
	if m != nil {
		return m.History
	}
	return nil
}

type PackageCrawl struct {
	JobStartedAt         *timestamp.Timestamp `protobuf:"bytes,1,opt,name=job_started_at,json=jobStartedAt,proto3" json:"job_started_at,omitempty"`
	JobFinishedAt        *timestamp.Timestamp `protobuf:"bytes,2,opt,name=job_finished_at,json=jobFinishedAt,proto3" json:"job_finished_at,omitempty"`
	JobReason            string               `protobuf:"bytes,3,opt,name=job_reason,json=jobReason,proto3" json:"job_reason,omitempty"`
	JobSucceeded         string               `protobuf:"bytes,4,opt,name=job_succeeded,json=jobSucceeded,proto3" json:"job_succeeded,omitempty"`
	JobMessages          string               `protobuf:"bytes,5,opt,name=job_messages,json=jobMessages,proto3" json:"job_messages,omitempty"`
	Data                 *PackageSnapshot     `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PackageCrawl) Reset()         { *m = PackageCrawl{} }
func (m *PackageCrawl) String() string { return proto.CompactTextString(m) }
func (*PackageCrawl) ProtoMessage()    {}
func (*PackageCrawl) Descriptor() ([]byte, []int) {
	return fileDescriptor_package_efc98af9608bae55, []int{1}
}
func (m *PackageCrawl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PackageCrawl.Unmarshal(m, b)
}
func (m *PackageCrawl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PackageCrawl.Marshal(b, m, deterministic)
}
func (dst *PackageCrawl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageCrawl.Merge(dst, src)
}
func (m *PackageCrawl) XXX_Size() int {
	return xxx_messageInfo_PackageCrawl.Size(m)
}
func (m *PackageCrawl) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageCrawl.DiscardUnknown(m)
}

var xxx_messageInfo_PackageCrawl proto.InternalMessageInfo

func (m *PackageCrawl) GetJobStartedAt() *timestamp.Timestamp {
	if m != nil {
		return m.JobStartedAt
	}
	return nil
}

func (m *PackageCrawl) GetJobFinishedAt() *timestamp.Timestamp {
	if m != nil {
		return m.JobFinishedAt
	}
	return nil
}

func (m *PackageCrawl) GetJobReason() string {
	if m != nil {
		return m.JobReason
	}
	return ""
}

func (m *PackageCrawl) GetJobSucceeded() string {
	if m != nil {
		return m.JobSucceeded
	}
	return ""
}

func (m *PackageCrawl) GetJobMessages() string {
	if m != nil {
		return m.JobMessages
	}
	return ""
}

func (m *PackageCrawl) GetData() *PackageSnapshot {
	if m != nil {
		return m.Data
	}
	return nil
}

type PackageSnapshot struct {
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Imports              []string             `protobuf:"bytes,2,rep,name=imports,proto3" json:"imports,omitempty"`
	TestImports          []string             `protobuf:"bytes,3,rep,name=test_imports,json=testImports,proto3" json:"test_imports,omitempty"`
	Commits              int32                `protobuf:"varint,4,opt,name=commits,proto3" json:"commits,omitempty"`
	Branches             int32                `protobuf:"varint,5,opt,name=branches,proto3" json:"branches,omitempty"`
	Tags                 int32                `protobuf:"varint,6,opt,name=tags,proto3" json:"tags,omitempty"`
	Bytes                int64                `protobuf:"varint,7,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Forks                int32                `protobuf:"varint,8,opt,name=forks,proto3" json:"forks,omitempty"`
	Stars                int32                `protobuf:"varint,9,opt,name=stars,proto3" json:"stars,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PackageSnapshot) Reset()         { *m = PackageSnapshot{} }
func (m *PackageSnapshot) String() string { return proto.CompactTextString(m) }
func (*PackageSnapshot) ProtoMessage()    {}
func (*PackageSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_package_efc98af9608bae55, []int{2}
}
func (m *PackageSnapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PackageSnapshot.Unmarshal(m, b)
}
func (m *PackageSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PackageSnapshot.Marshal(b, m, deterministic)
}
func (dst *PackageSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageSnapshot.Merge(dst, src)
}
func (m *PackageSnapshot) XXX_Size() int {
	return xxx_messageInfo_PackageSnapshot.Size(m)
}
func (m *PackageSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_PackageSnapshot proto.InternalMessageInfo

func (m *PackageSnapshot) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *PackageSnapshot) GetImports() []string {
	if m != nil {
		return m.Imports
	}
	return nil
}

func (m *PackageSnapshot) GetTestImports() []string {
	if m != nil {
		return m.TestImports
	}
	return nil
}

func (m *PackageSnapshot) GetCommits() int32 {
	if m != nil {
		return m.Commits
	}
	return 0
}

func (m *PackageSnapshot) GetBranches() int32 {
	if m != nil {
		return m.Branches
	}
	return 0
}

func (m *PackageSnapshot) GetTags() int32 {
	if m != nil {
		return m.Tags
	}
	return 0
}

func (m *PackageSnapshot) GetBytes() int64 {
	if m != nil {
		return m.Bytes
	}
	return 0
}

func (m *PackageSnapshot) GetForks() int32 {
	if m != nil {
		return m.Forks
	}
	return 0
}

func (m *PackageSnapshot) GetStars() int32 {
	if m != nil {
		return m.Stars
	}
	return 0
}

func init() {
	proto.RegisterType((*Package)(nil), "domain.Package")
	proto.RegisterType((*PackageCrawl)(nil), "domain.PackageCrawl")
	proto.RegisterType((*PackageSnapshot)(nil), "domain.PackageSnapshot")
}

func init() { proto.RegisterFile("package.proto", fileDescriptor_package_efc98af9608bae55) }

var fileDescriptor_package_efc98af9608bae55 = []byte{
	// 473 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcd, 0x8a, 0xd4, 0x40,
	0x10, 0xc7, 0xc9, 0x64, 0x93, 0x6c, 0x2a, 0x3b, 0xae, 0x34, 0x8b, 0x36, 0x03, 0x62, 0x1c, 0x2f,
	0x01, 0x21, 0x0b, 0xeb, 0xc9, 0x8b, 0x38, 0x0a, 0x82, 0x07, 0x41, 0x7a, 0xbc, 0x87, 0x4e, 0xd2,
	0x93, 0x8f, 0x9d, 0xa4, 0x43, 0x77, 0x0d, 0xb2, 0x0f, 0xe2, 0x3b, 0xf8, 0x88, 0x1e, 0xa5, 0xbb,
	0x93, 0x45, 0xf6, 0xb2, 0x7b, 0xab, 0xff, 0xaf, 0x3e, 0x52, 0xff, 0x4a, 0xc3, 0x7a, 0xe2, 0xd5,
	0x2d, 0x6f, 0x44, 0x3e, 0x29, 0x89, 0x92, 0x84, 0xb5, 0x1c, 0x78, 0x37, 0x6e, 0x5e, 0x37, 0x52,
	0x36, 0x47, 0x71, 0x6d, 0x69, 0x79, 0x3a, 0x5c, 0x63, 0x37, 0x08, 0x8d, 0x7c, 0x98, 0x5c, 0xe1,
	0xf6, 0xaf, 0x07, 0xd1, 0x0f, 0xd7, 0x4a, 0x08, 0x9c, 0x8d, 0x7c, 0x10, 0xd4, 0x4b, 0xbd, 0x2c,
	0x66, 0x36, 0x36, 0x6c, 0xe2, 0xd8, 0xd2, 0x95, 0x63, 0x26, 0x26, 0xcf, 0xc1, 0x3f, 0xa9, 0x23,
	0xf5, 0x2d, 0x32, 0x21, 0x79, 0x01, 0x21, 0x3f, 0x61, 0x2b, 0x15, 0x3d, 0xb3, 0x70, 0x56, 0xe4,
	0x1d, 0x9c, 0xd5, 0x1c, 0x39, 0x0d, 0x52, 0x2f, 0x4b, 0x6e, 0x5e, 0xe6, 0x6e, 0xab, 0x7c, 0xfe,
	0xe0, 0x7e, 0xe4, 0x93, 0x6e, 0x25, 0x32, 0x5b, 0x44, 0x3e, 0xc2, 0xfa, 0xd0, 0x29, 0x8d, 0x85,
	0x16, 0x62, 0x2c, 0x38, 0xd2, 0xd0, 0x76, 0x6d, 0x72, 0xe7, 0x21, 0x5f, 0x3c, 0xe4, 0x3f, 0x17,
	0x0f, 0x2c, 0xb1, 0x0d, 0x7b, 0x21, 0xc6, 0x1d, 0x92, 0x1c, 0xa2, 0xb6, 0xd3, 0x28, 0xd5, 0x1d,
	0x8d, 0x52, 0x3f, 0x4b, 0x6e, 0xae, 0x1e, 0x7c, 0xef, 0x8b, 0xe2, 0xbf, 0x8e, 0x6c, 0x29, 0xda,
	0xfe, 0x59, 0xc1, 0xc5, 0xff, 0x19, 0xf2, 0x09, 0x9e, 0xf5, 0xb2, 0x2c, 0x34, 0x72, 0x85, 0xa2,
	0x36, 0x1b, 0x78, 0x8f, 0x6e, 0x70, 0xd1, 0xcb, 0x72, 0xef, 0x1a, 0x76, 0x48, 0x3e, 0xc3, 0xa5,
	0x99, 0x70, 0xe8, 0xc6, 0x4e, 0xb7, 0x6e, 0xc4, 0xea, 0xd1, 0x11, 0xeb, 0x5e, 0x96, 0x5f, 0xe7,
	0x8e, 0x1d, 0x92, 0x57, 0x00, 0x66, 0x86, 0x12, 0x5c, 0xcb, 0x71, 0x3e, 0x72, 0xdc, 0xcb, 0x92,
	0x59, 0x40, 0xde, 0xc2, 0xda, 0x2e, 0x79, 0xaa, 0x2a, 0x21, 0x6a, 0x51, 0xcf, 0x17, 0xb7, 0x7b,
	0x2c, 0x8c, 0xbc, 0x01, 0xa3, 0x8b, 0x41, 0x68, 0xcd, 0x1b, 0xa1, 0xed, 0xfd, 0x63, 0x96, 0xf4,
	0xb2, 0xfc, 0x3e, 0xa3, 0xfb, 0x5f, 0x13, 0x3e, 0xe1, 0xd7, 0x6c, 0x7f, 0xaf, 0xe0, 0xf2, 0x41,
	0x86, 0x7c, 0x00, 0xa8, 0x94, 0xe0, 0x4f, 0xbe, 0x54, 0x3c, 0x57, 0xef, 0x90, 0x50, 0x88, 0xba,
	0x61, 0x92, 0x0a, 0x35, 0x5d, 0xa5, 0x7e, 0x16, 0xb3, 0x45, 0x9a, 0xc5, 0x51, 0x68, 0x2c, 0x96,
	0xb4, 0x6f, 0xd3, 0x89, 0x61, 0xdf, 0xe6, 0x12, 0x0a, 0x51, 0x25, 0x87, 0xa1, 0x43, 0x6d, 0xad,
	0x07, 0x6c, 0x91, 0x64, 0x03, 0xe7, 0xa5, 0xe2, 0x63, 0xd5, 0xce, 0x8e, 0x03, 0x76, 0xaf, 0xcd,
	0x3b, 0x46, 0xde, 0x68, 0x6b, 0x37, 0x60, 0x36, 0x26, 0x57, 0x10, 0x94, 0x77, 0x28, 0x34, 0x8d,
	0x52, 0x2f, 0xf3, 0x99, 0x13, 0x86, 0x1e, 0xa4, 0xba, 0xd5, 0xf4, 0xdc, 0x96, 0x3a, 0x61, 0xa8,
	0x79, 0x17, 0x9a, 0xc6, 0x8e, 0x5a, 0x51, 0x86, 0xd6, 0xe7, 0xfb, 0x7f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xbd, 0x21, 0x7f, 0xa6, 0x7e, 0x03, 0x00, 0x00,
}
