// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pending_references.proto

package domain

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/infobloxopen/protoc-gen-gorm/options"

import time "time"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

func (this *PendingReferences) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
