// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: remote_crawler.proto

package domain

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/types"
import _ "github.com/gogo/protobuf/types"
import _ "github.com/gogo/protobuf/types"
import _ "github.com/gogo/googleapis/google/api"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/mwitkow/go-proto-validators"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CrawlResult struct {
	Package           *Package                      `protobuf:"bytes,1,opt,name=Package" json:"Package,omitempty"`
	ImportedResources map[string]*PackageReferences `protobuf:"bytes,2,rep,name=imported_resources,json=importedResources" json:"imported_resources,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value"`
	ErrMsg            string                        `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
}

func (m *CrawlResult) Reset()                    { *m = CrawlResult{} }
func (m *CrawlResult) String() string            { return proto.CompactTextString(m) }
func (*CrawlResult) ProtoMessage()               {}
func (*CrawlResult) Descriptor() ([]byte, []int) { return fileDescriptorRemoteCrawler, []int{0} }

func (m *CrawlResult) GetPackage() *Package {
	if m != nil {
		return m.Package
	}
	return nil
}

func (m *CrawlResult) GetImportedResources() map[string]*PackageReferences {
	if m != nil {
		return m.ImportedResources
	}
	return nil
}

func (m *CrawlResult) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (*CrawlResult) XXX_MessageName() string {
	return "domain.CrawlResult"
}

type EnqueueRequest struct {
	Entries  []*ToCrawlEntry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	Priority int32           `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
}

func (m *EnqueueRequest) Reset()                    { *m = EnqueueRequest{} }
func (m *EnqueueRequest) String() string            { return proto.CompactTextString(m) }
func (*EnqueueRequest) ProtoMessage()               {}
func (*EnqueueRequest) Descriptor() ([]byte, []int) { return fileDescriptorRemoteCrawler, []int{1} }

func (m *EnqueueRequest) GetEntries() []*ToCrawlEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *EnqueueRequest) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (*EnqueueRequest) XXX_MessageName() string {
	return "domain.EnqueueRequest"
}

type EnqueueResponse struct {
	N int32 `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
}

func (m *EnqueueResponse) Reset()                    { *m = EnqueueResponse{} }
func (m *EnqueueResponse) String() string            { return proto.CompactTextString(m) }
func (*EnqueueResponse) ProtoMessage()               {}
func (*EnqueueResponse) Descriptor() ([]byte, []int) { return fileDescriptorRemoteCrawler, []int{2} }

func (m *EnqueueResponse) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

func (*EnqueueResponse) XXX_MessageName() string {
	return "domain.EnqueueResponse"
}

type OperationResult struct {
	ErrMsg string `protobuf:"bytes,1,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
}

func (m *OperationResult) Reset()                    { *m = OperationResult{} }
func (m *OperationResult) String() string            { return proto.CompactTextString(m) }
func (*OperationResult) ProtoMessage()               {}
func (*OperationResult) Descriptor() ([]byte, []int) { return fileDescriptorRemoteCrawler, []int{3} }

func (m *OperationResult) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (*OperationResult) XXX_MessageName() string {
	return "domain.OperationResult"
}
func init() {
	proto.RegisterType((*CrawlResult)(nil), "domain.CrawlResult")
	proto.RegisterType((*EnqueueRequest)(nil), "domain.EnqueueRequest")
	proto.RegisterType((*EnqueueResponse)(nil), "domain.EnqueueResponse")
	proto.RegisterType((*OperationResult)(nil), "domain.OperationResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RemoteCrawlerService service

type RemoteCrawlerServiceClient interface {
	Attach(ctx context.Context, opts ...grpc.CallOption) (RemoteCrawlerService_AttachClient, error)
	Receive(ctx context.Context, in *CrawlResult, opts ...grpc.CallOption) (*OperationResult, error)
	Enqueue(ctx context.Context, in *EnqueueRequest, opts ...grpc.CallOption) (*EnqueueResponse, error)
}

type remoteCrawlerServiceClient struct {
	cc *grpc.ClientConn
}

func NewRemoteCrawlerServiceClient(cc *grpc.ClientConn) RemoteCrawlerServiceClient {
	return &remoteCrawlerServiceClient{cc}
}

func (c *remoteCrawlerServiceClient) Attach(ctx context.Context, opts ...grpc.CallOption) (RemoteCrawlerService_AttachClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RemoteCrawlerService_serviceDesc.Streams[0], c.cc, "/domain.RemoteCrawlerService/Attach", opts...)
	if err != nil {
		return nil, err
	}
	x := &remoteCrawlerServiceAttachClient{stream}
	return x, nil
}

type RemoteCrawlerService_AttachClient interface {
	Send(*CrawlResult) error
	Recv() (*ToCrawlEntry, error)
	grpc.ClientStream
}

type remoteCrawlerServiceAttachClient struct {
	grpc.ClientStream
}

func (x *remoteCrawlerServiceAttachClient) Send(m *CrawlResult) error {
	return x.ClientStream.SendMsg(m)
}

func (x *remoteCrawlerServiceAttachClient) Recv() (*ToCrawlEntry, error) {
	m := new(ToCrawlEntry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *remoteCrawlerServiceClient) Receive(ctx context.Context, in *CrawlResult, opts ...grpc.CallOption) (*OperationResult, error) {
	out := new(OperationResult)
	err := grpc.Invoke(ctx, "/domain.RemoteCrawlerService/Receive", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteCrawlerServiceClient) Enqueue(ctx context.Context, in *EnqueueRequest, opts ...grpc.CallOption) (*EnqueueResponse, error) {
	out := new(EnqueueResponse)
	err := grpc.Invoke(ctx, "/domain.RemoteCrawlerService/Enqueue", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RemoteCrawlerService service

type RemoteCrawlerServiceServer interface {
	Attach(RemoteCrawlerService_AttachServer) error
	Receive(context.Context, *CrawlResult) (*OperationResult, error)
	Enqueue(context.Context, *EnqueueRequest) (*EnqueueResponse, error)
}

func RegisterRemoteCrawlerServiceServer(s *grpc.Server, srv RemoteCrawlerServiceServer) {
	s.RegisterService(&_RemoteCrawlerService_serviceDesc, srv)
}

func _RemoteCrawlerService_Attach_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RemoteCrawlerServiceServer).Attach(&remoteCrawlerServiceAttachServer{stream})
}

type RemoteCrawlerService_AttachServer interface {
	Send(*ToCrawlEntry) error
	Recv() (*CrawlResult, error)
	grpc.ServerStream
}

type remoteCrawlerServiceAttachServer struct {
	grpc.ServerStream
}

func (x *remoteCrawlerServiceAttachServer) Send(m *ToCrawlEntry) error {
	return x.ServerStream.SendMsg(m)
}

func (x *remoteCrawlerServiceAttachServer) Recv() (*CrawlResult, error) {
	m := new(CrawlResult)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _RemoteCrawlerService_Receive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrawlResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteCrawlerServiceServer).Receive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/domain.RemoteCrawlerService/Receive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteCrawlerServiceServer).Receive(ctx, req.(*CrawlResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteCrawlerService_Enqueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteCrawlerServiceServer).Enqueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/domain.RemoteCrawlerService/Enqueue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteCrawlerServiceServer).Enqueue(ctx, req.(*EnqueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RemoteCrawlerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "domain.RemoteCrawlerService",
	HandlerType: (*RemoteCrawlerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Receive",
			Handler:    _RemoteCrawlerService_Receive_Handler,
		},
		{
			MethodName: "Enqueue",
			Handler:    _RemoteCrawlerService_Enqueue_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Attach",
			Handler:       _RemoteCrawlerService_Attach_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "remote_crawler.proto",
}

func (m *CrawlResult) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CrawlResult) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Package != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintRemoteCrawler(dAtA, i, uint64(m.Package.Size()))
		n1, err := m.Package.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.ImportedResources) > 0 {
		for k, _ := range m.ImportedResources {
			dAtA[i] = 0x12
			i++
			v := m.ImportedResources[k]
			msgSize := 0
			if v != nil {
				msgSize = v.Size()
				msgSize += 1 + sovRemoteCrawler(uint64(msgSize))
			}
			mapSize := 1 + len(k) + sovRemoteCrawler(uint64(len(k))) + msgSize
			i = encodeVarintRemoteCrawler(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintRemoteCrawler(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			if v != nil {
				dAtA[i] = 0x12
				i++
				i = encodeVarintRemoteCrawler(dAtA, i, uint64(v.Size()))
				n2, err := v.MarshalTo(dAtA[i:])
				if err != nil {
					return 0, err
				}
				i += n2
			}
		}
	}
	if len(m.ErrMsg) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintRemoteCrawler(dAtA, i, uint64(len(m.ErrMsg)))
		i += copy(dAtA[i:], m.ErrMsg)
	}
	return i, nil
}

func (m *EnqueueRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EnqueueRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Entries) > 0 {
		for _, msg := range m.Entries {
			dAtA[i] = 0xa
			i++
			i = encodeVarintRemoteCrawler(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.Priority != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintRemoteCrawler(dAtA, i, uint64(m.Priority))
	}
	return i, nil
}

func (m *EnqueueResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EnqueueResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.N != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintRemoteCrawler(dAtA, i, uint64(m.N))
	}
	return i, nil
}

func (m *OperationResult) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OperationResult) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ErrMsg) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintRemoteCrawler(dAtA, i, uint64(len(m.ErrMsg)))
		i += copy(dAtA[i:], m.ErrMsg)
	}
	return i, nil
}

func encodeVarintRemoteCrawler(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *CrawlResult) Size() (n int) {
	var l int
	_ = l
	if m.Package != nil {
		l = m.Package.Size()
		n += 1 + l + sovRemoteCrawler(uint64(l))
	}
	if len(m.ImportedResources) > 0 {
		for k, v := range m.ImportedResources {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovRemoteCrawler(uint64(l))
			}
			mapEntrySize := 1 + len(k) + sovRemoteCrawler(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovRemoteCrawler(uint64(mapEntrySize))
		}
	}
	l = len(m.ErrMsg)
	if l > 0 {
		n += 1 + l + sovRemoteCrawler(uint64(l))
	}
	return n
}

func (m *EnqueueRequest) Size() (n int) {
	var l int
	_ = l
	if len(m.Entries) > 0 {
		for _, e := range m.Entries {
			l = e.Size()
			n += 1 + l + sovRemoteCrawler(uint64(l))
		}
	}
	if m.Priority != 0 {
		n += 1 + sovRemoteCrawler(uint64(m.Priority))
	}
	return n
}

func (m *EnqueueResponse) Size() (n int) {
	var l int
	_ = l
	if m.N != 0 {
		n += 1 + sovRemoteCrawler(uint64(m.N))
	}
	return n
}

func (m *OperationResult) Size() (n int) {
	var l int
	_ = l
	l = len(m.ErrMsg)
	if l > 0 {
		n += 1 + l + sovRemoteCrawler(uint64(l))
	}
	return n
}

func sovRemoteCrawler(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozRemoteCrawler(x uint64) (n int) {
	return sovRemoteCrawler(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CrawlResult) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRemoteCrawler
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CrawlResult: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CrawlResult: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Package", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRemoteCrawler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRemoteCrawler
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Package == nil {
				m.Package = &Package{}
			}
			if err := m.Package.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ImportedResources", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRemoteCrawler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRemoteCrawler
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ImportedResources == nil {
				m.ImportedResources = make(map[string]*PackageReferences)
			}
			var mapkey string
			var mapvalue *PackageReferences
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRemoteCrawler
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowRemoteCrawler
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthRemoteCrawler
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowRemoteCrawler
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= (int(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthRemoteCrawler
					}
					postmsgIndex := iNdEx + mapmsglen
					if mapmsglen < 0 {
						return ErrInvalidLengthRemoteCrawler
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &PackageReferences{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipRemoteCrawler(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthRemoteCrawler
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.ImportedResources[mapkey] = mapvalue
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrMsg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRemoteCrawler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRemoteCrawler
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ErrMsg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRemoteCrawler(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRemoteCrawler
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EnqueueRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRemoteCrawler
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EnqueueRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EnqueueRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRemoteCrawler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRemoteCrawler
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Entries = append(m.Entries, &ToCrawlEntry{})
			if err := m.Entries[len(m.Entries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Priority", wireType)
			}
			m.Priority = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRemoteCrawler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Priority |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRemoteCrawler(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRemoteCrawler
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EnqueueResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRemoteCrawler
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EnqueueResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EnqueueResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field N", wireType)
			}
			m.N = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRemoteCrawler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.N |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRemoteCrawler(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRemoteCrawler
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OperationResult) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRemoteCrawler
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OperationResult: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OperationResult: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrMsg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRemoteCrawler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRemoteCrawler
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ErrMsg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRemoteCrawler(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRemoteCrawler
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRemoteCrawler(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRemoteCrawler
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRemoteCrawler
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRemoteCrawler
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthRemoteCrawler
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowRemoteCrawler
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipRemoteCrawler(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthRemoteCrawler = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRemoteCrawler   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("remote_crawler.proto", fileDescriptorRemoteCrawler) }

var fileDescriptorRemoteCrawler = []byte{
	// 660 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x71, 0xab, 0xb6, 0xcc, 0x83, 0x15, 0xbc, 0x6a, 0x74, 0x05, 0x75, 0x51, 0x4e, 0x5d,
	0x45, 0x93, 0xad, 0x48, 0x08, 0xf5, 0x36, 0xc6, 0x34, 0x21, 0x81, 0x40, 0x19, 0x42, 0x80, 0x90,
	0x2a, 0x37, 0x7d, 0xcb, 0x4c, 0x93, 0x38, 0xb3, 0x9d, 0x96, 0x5e, 0x39, 0x73, 0x62, 0x07, 0xf8,
	0x38, 0x1c, 0x77, 0x44, 0xe2, 0x0b, 0xa0, 0x8d, 0x0f, 0x82, 0xea, 0x38, 0xdb, 0x28, 0xe5, 0x14,
	0xbf, 0xe7, 0xdf, 0xfb, 0xe7, 0xbd, 0xbf, 0x6d, 0x5c, 0x13, 0x10, 0x71, 0x05, 0x7d, 0x5f, 0xd0,
	0x49, 0x08, 0xc2, 0x49, 0x04, 0x57, 0x9c, 0x94, 0x87, 0x3c, 0xa2, 0x2c, 0x6e, 0xdc, 0x0d, 0x38,
	0x0f, 0x42, 0x70, 0x75, 0x76, 0x90, 0x1e, 0xba, 0x10, 0x25, 0x6a, 0x9a, 0x41, 0x8d, 0x8d, 0xf9,
	0x4d, 0xc5, 0x22, 0x90, 0x8a, 0x46, 0x89, 0x01, 0xac, 0x79, 0xe0, 0x90, 0x41, 0x38, 0xec, 0x47,
	0x54, 0x8e, 0x0c, 0x71, 0xcf, 0x10, 0x34, 0x61, 0x2e, 0x8d, 0x63, 0xae, 0xa8, 0x62, 0x3c, 0x96,
	0x66, 0xf7, 0xbe, 0xfe, 0xf8, 0x9d, 0x00, 0xe2, 0x8e, 0x9c, 0xd0, 0x20, 0x00, 0xe1, 0xf2, 0x44,
	0x13, 0x0b, 0xe8, 0x4e, 0xc0, 0xd4, 0x51, 0x3a, 0x70, 0x7c, 0x1e, 0xb9, 0x01, 0x0f, 0xf8, 0xe5,
	0x6f, 0x67, 0x91, 0x0e, 0xf4, 0xca, 0xe0, 0x0f, 0xaf, 0xe0, 0xd1, 0x84, 0xa9, 0x11, 0x9f, 0xb8,
	0x01, 0xef, 0xe8, 0xcd, 0xce, 0x98, 0x86, 0x6c, 0x48, 0x15, 0x17, 0xd2, 0xbd, 0x58, 0x9a, 0xba,
	0x9b, 0x09, 0xf5, 0x47, 0x34, 0x00, 0x13, 0x12, 0xc5, 0x33, 0xeb, 0x62, 0x25, 0x8c, 0x31, 0xf6,
	0xe7, 0x02, 0x5e, 0xde, 0x9d, 0x25, 0x3d, 0x90, 0x69, 0xa8, 0xc8, 0x26, 0xae, 0xbc, 0xcc, 0x8a,
	0xea, 0xc8, 0x42, 0xad, 0xe5, 0x6e, 0xd5, 0xc9, 0xfc, 0x75, 0x4c, 0xda, 0xcb, 0xf7, 0xc9, 0x5b,
	0x4c, 0x58, 0x94, 0x70, 0xa1, 0x60, 0xd8, 0x17, 0x20, 0x79, 0x2a, 0x7c, 0x90, 0xf5, 0x82, 0x55,
	0x6c, 0x2d, 0x77, 0xdb, 0x79, 0xd5, 0x15, 0x6d, 0xe7, 0xa9, 0xa1, 0xbd, 0x1c, 0xde, 0x9b, 0x35,
	0xe2, 0xdd, 0x66, 0xf3, 0x79, 0xb2, 0x86, 0xcb, 0x7b, 0x42, 0x3c, 0x97, 0x41, 0xbd, 0x68, 0xa1,
	0xd6, 0x92, 0x67, 0xa2, 0x46, 0x1f, 0xaf, 0x2d, 0x16, 0x21, 0xb7, 0x70, 0x71, 0x04, 0x53, 0xdd,
	0xf3, 0x92, 0x37, 0x5b, 0x12, 0x17, 0x97, 0xc6, 0x34, 0x4c, 0xa1, 0x5e, 0xd0, 0x73, 0xac, 0xcf,
	0xcf, 0x01, 0x87, 0x20, 0x20, 0xf6, 0x41, 0x7a, 0x19, 0xd7, 0x2b, 0x3c, 0x42, 0xf6, 0x7b, 0xbc,
	0xb2, 0x17, 0x1f, 0xa7, 0x90, 0x82, 0x07, 0xc7, 0x29, 0x48, 0x45, 0x1c, 0x5c, 0x99, 0xf9, 0xc5,
	0x40, 0xd6, 0x91, 0x1e, 0xad, 0x96, 0x0b, 0xbd, 0xe2, 0x7a, 0xb8, 0x6c, 0x88, 0x1c, 0x22, 0x0d,
	0x7c, 0x3d, 0x11, 0x8c, 0x0b, 0xa6, 0xa6, 0xfa, 0xcf, 0x25, 0xef, 0x22, 0xb6, 0x37, 0x70, 0xf5,
	0x42, 0x5d, 0x26, 0x3c, 0x96, 0x40, 0x6e, 0x60, 0x14, 0xeb, 0xae, 0x4b, 0x1e, 0x8a, 0xed, 0x4d,
	0x5c, 0x7d, 0x91, 0x80, 0xd0, 0x77, 0xc5, 0x1c, 0xc8, 0xa5, 0x15, 0xe8, 0xaa, 0x15, 0xdd, 0xaf,
	0x05, 0x5c, 0xf3, 0xf4, 0x7b, 0xd8, 0xcd, 0x9e, 0xc3, 0x01, 0x88, 0x31, 0xf3, 0x81, 0x78, 0xb8,
	0xbc, 0xa3, 0x14, 0xf5, 0x8f, 0xc8, 0xea, 0x82, 0x43, 0x68, 0x2c, 0x6c, 0xdf, 0x5e, 0xff, 0xf4,
	0xf3, 0xf7, 0x49, 0x61, 0xd5, 0x5e, 0xd1, 0xd7, 0x7b, 0xbc, 0xed, 0x52, 0x2d, 0xd1, 0x43, 0xed,
	0x16, 0xda, 0x42, 0xe4, 0x00, 0x57, 0x3c, 0xf0, 0x81, 0x8d, 0x61, 0xb1, 0xe8, 0x9d, 0x3c, 0x39,
	0xd7, 0xbd, 0xdd, 0xd0, 0xba, 0x35, 0xbb, 0x9a, 0xeb, 0x8a, 0x4c, 0xa6, 0x87, 0xda, 0xe4, 0x35,
	0xae, 0x18, 0x37, 0xc8, 0x5a, 0x5e, 0xff, 0xb7, 0xf9, 0x97, 0xba, 0x73, 0xb6, 0xfd, 0xab, 0x0b,
	0x19, 0xd0, 0x43, 0xed, 0xc7, 0x27, 0xe8, 0xcb, 0xce, 0x1b, 0x52, 0xea, 0x16, 0xb7, 0x9d, 0xad,
	0x36, 0x2a, 0x88, 0x67, 0x78, 0x73, 0x27, 0x1e, 0x0a, 0x1e, 0xc1, 0x90, 0x5a, 0xfb, 0x34, 0xa4,
	0x1f, 0xa7, 0xd6, 0x3e, 0x0f, 0x69, 0x1c, 0x58, 0xe6, 0x2e, 0x48, 0xeb, 0x09, 0x55, 0x74, 0x40,
	0x25, 0x90, 0x8d, 0x23, 0xa5, 0x12, 0xd9, 0x73, 0xdd, 0x0f, 0x74, 0xaa, 0xe8, 0x34, 0xe4, 0x42,
	0xbf, 0x3a, 0x9a, 0x0b, 0x9c, 0x9e, 0x35, 0xd1, 0x8f, 0xb3, 0x26, 0xfa, 0x75, 0xd6, 0x44, 0xdf,
	0xce, 0x9b, 0xd7, 0xbe, 0x9f, 0x37, 0xd1, 0xe9, 0x79, 0x13, 0xbd, 0x6b, 0xfe, 0xa7, 0xc0, 0xcd,
	0x26, 0x18, 0x94, 0xf5, 0x7b, 0x7b, 0xf0, 0x27, 0x00, 0x00, 0xff, 0xff, 0xae, 0x10, 0x7d, 0x73,
	0xc5, 0x04, 0x00, 0x00,
}
