// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: remote_crawler.proto

package domain

import go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/gogo/protobuf/proto"
import golang_proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/types"
import _ "github.com/gogo/protobuf/types"
import _ "github.com/gogo/protobuf/types"
import _ "github.com/gogo/googleapis/google/api"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/mwitkow/go-proto-validators"

import time "time"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

func (this *CrawlResult) Validate() error {
	if this.Package != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Package); err != nil {
			return go_proto_validators.FieldError("Package", err)
		}
	}
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
