// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: remote_crawler.proto

package domain

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/types"
import _ "github.com/gogo/protobuf/types"
import _ "github.com/gogo/protobuf/types"
import _ "github.com/gogo/googleapis/google/api"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/mwitkow/go-proto-validators"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CrawlResult struct {
	Package *Package `protobuf:"bytes,1,opt,name=Package" json:"Package,omitempty"`
	Error   string   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (m *CrawlResult) Reset()                    { *m = CrawlResult{} }
func (m *CrawlResult) String() string            { return proto.CompactTextString(m) }
func (*CrawlResult) ProtoMessage()               {}
func (*CrawlResult) Descriptor() ([]byte, []int) { return fileDescriptorRemoteCrawler, []int{0} }

func (m *CrawlResult) GetPackage() *Package {
	if m != nil {
		return m.Package
	}
	return nil
}

func (m *CrawlResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (*CrawlResult) XXX_MessageName() string {
	return "domain.CrawlResult"
}
func init() {
	proto.RegisterType((*CrawlResult)(nil), "domain.CrawlResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RemoteCrawlerService service

type RemoteCrawlerServiceClient interface {
	// rpc Next() returns (ToCrawlEntry) {}
	Attach(ctx context.Context, opts ...grpc.CallOption) (RemoteCrawlerService_AttachClient, error)
}

type remoteCrawlerServiceClient struct {
	cc *grpc.ClientConn
}

func NewRemoteCrawlerServiceClient(cc *grpc.ClientConn) RemoteCrawlerServiceClient {
	return &remoteCrawlerServiceClient{cc}
}

func (c *remoteCrawlerServiceClient) Attach(ctx context.Context, opts ...grpc.CallOption) (RemoteCrawlerService_AttachClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RemoteCrawlerService_serviceDesc.Streams[0], c.cc, "/domain.RemoteCrawlerService/Attach", opts...)
	if err != nil {
		return nil, err
	}
	x := &remoteCrawlerServiceAttachClient{stream}
	return x, nil
}

type RemoteCrawlerService_AttachClient interface {
	Send(*CrawlResult) error
	Recv() (*ToCrawlEntry, error)
	grpc.ClientStream
}

type remoteCrawlerServiceAttachClient struct {
	grpc.ClientStream
}

func (x *remoteCrawlerServiceAttachClient) Send(m *CrawlResult) error {
	return x.ClientStream.SendMsg(m)
}

func (x *remoteCrawlerServiceAttachClient) Recv() (*ToCrawlEntry, error) {
	m := new(ToCrawlEntry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for RemoteCrawlerService service

type RemoteCrawlerServiceServer interface {
	// rpc Next() returns (ToCrawlEntry) {}
	Attach(RemoteCrawlerService_AttachServer) error
}

func RegisterRemoteCrawlerServiceServer(s *grpc.Server, srv RemoteCrawlerServiceServer) {
	s.RegisterService(&_RemoteCrawlerService_serviceDesc, srv)
}

func _RemoteCrawlerService_Attach_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RemoteCrawlerServiceServer).Attach(&remoteCrawlerServiceAttachServer{stream})
}

type RemoteCrawlerService_AttachServer interface {
	Send(*ToCrawlEntry) error
	Recv() (*CrawlResult, error)
	grpc.ServerStream
}

type remoteCrawlerServiceAttachServer struct {
	grpc.ServerStream
}

func (x *remoteCrawlerServiceAttachServer) Send(m *ToCrawlEntry) error {
	return x.ServerStream.SendMsg(m)
}

func (x *remoteCrawlerServiceAttachServer) Recv() (*CrawlResult, error) {
	m := new(CrawlResult)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _RemoteCrawlerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "domain.RemoteCrawlerService",
	HandlerType: (*RemoteCrawlerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Attach",
			Handler:       _RemoteCrawlerService_Attach_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "remote_crawler.proto",
}

func (m *CrawlResult) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CrawlResult) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Package != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintRemoteCrawler(dAtA, i, uint64(m.Package.Size()))
		n1, err := m.Package.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.Error) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintRemoteCrawler(dAtA, i, uint64(len(m.Error)))
		i += copy(dAtA[i:], m.Error)
	}
	return i, nil
}

func encodeVarintRemoteCrawler(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *CrawlResult) Size() (n int) {
	var l int
	_ = l
	if m.Package != nil {
		l = m.Package.Size()
		n += 1 + l + sovRemoteCrawler(uint64(l))
	}
	l = len(m.Error)
	if l > 0 {
		n += 1 + l + sovRemoteCrawler(uint64(l))
	}
	return n
}

func sovRemoteCrawler(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozRemoteCrawler(x uint64) (n int) {
	return sovRemoteCrawler(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CrawlResult) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRemoteCrawler
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CrawlResult: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CrawlResult: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Package", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRemoteCrawler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRemoteCrawler
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Package == nil {
				m.Package = &Package{}
			}
			if err := m.Package.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRemoteCrawler
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRemoteCrawler
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Error = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRemoteCrawler(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRemoteCrawler
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRemoteCrawler(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRemoteCrawler
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRemoteCrawler
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRemoteCrawler
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthRemoteCrawler
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowRemoteCrawler
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipRemoteCrawler(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthRemoteCrawler = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRemoteCrawler   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("remote_crawler.proto", fileDescriptorRemoteCrawler) }

var fileDescriptorRemoteCrawler = []byte{
	// 443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xd9, 0xa0, 0x06, 0xe1, 0x0a, 0x90, 0xdc, 0x1c, 0x4a, 0x40, 0xae, 0x95, 0x53, 0x5a,
	0x61, 0x6f, 0x1b, 0x24, 0x0e, 0xbd, 0x85, 0x52, 0xf5, 0x82, 0x10, 0x32, 0x1c, 0x10, 0x97, 0x6a,
	0x62, 0x6f, 0x37, 0xdb, 0x78, 0x3d, 0xd6, 0xee, 0x24, 0x21, 0x57, 0x1e, 0x81, 0x5e, 0x78, 0x1c,
	0x8e, 0x3d, 0x22, 0xf1, 0x02, 0x28, 0xe1, 0x41, 0x50, 0xd6, 0x1b, 0xa8, 0x2a, 0x38, 0x79, 0xe7,
	0xff, 0xbf, 0x99, 0x5d, 0xff, 0x13, 0x74, 0x8c, 0xd0, 0x48, 0xe2, 0x3c, 0x37, 0x30, 0x2f, 0x85,
	0x49, 0x6b, 0x83, 0x84, 0x61, 0xbb, 0x40, 0x0d, 0xaa, 0xea, 0x3e, 0x91, 0x88, 0xb2, 0x14, 0xdc,
	0xa9, 0xa3, 0xe9, 0x05, 0x17, 0xba, 0xa6, 0x45, 0x03, 0x75, 0xf7, 0x6e, 0x9b, 0xa4, 0xb4, 0xb0,
	0x04, 0xba, 0xf6, 0x40, 0x7c, 0x1b, 0xb8, 0x50, 0xa2, 0x2c, 0xce, 0x35, 0xd8, 0x89, 0x27, 0x9e,
	0x7a, 0x02, 0x6a, 0xc5, 0xa1, 0xaa, 0x90, 0x80, 0x14, 0x56, 0xd6, 0xbb, 0xcf, 0xdc, 0x27, 0x4f,
	0xa4, 0xa8, 0x12, 0x3b, 0x07, 0x29, 0x85, 0xe1, 0x58, 0x3b, 0xe2, 0x1f, 0x74, 0x22, 0x15, 0x8d,
	0xa7, 0xa3, 0x34, 0x47, 0xcd, 0x25, 0x4a, 0xfc, 0x7b, 0xed, 0xba, 0x72, 0x85, 0x3b, 0x79, 0xfc,
	0xc5, 0x0d, 0x5c, 0xcf, 0x15, 0x4d, 0x70, 0xce, 0x25, 0x26, 0xce, 0x4c, 0x66, 0x50, 0xaa, 0x02,
	0x08, 0x8d, 0xe5, 0x7f, 0x8e, 0xbe, 0xef, 0x41, 0x0d, 0xf9, 0x04, 0xa4, 0xf0, 0x65, 0x48, 0xd8,
	0x44, 0x57, 0x91, 0xf1, 0xc1, 0xf4, 0xde, 0x04, 0xdb, 0x27, 0x6b, 0x2d, 0x13, 0x76, 0x5a, 0x52,
	0xb8, 0x1f, 0xdc, 0x7b, 0xdb, 0xf4, 0xec, 0xb2, 0x98, 0xf5, 0xb7, 0x07, 0x8f, 0xd2, 0x26, 0xde,
	0xd4, 0xcb, 0xd9, 0xc6, 0x0f, 0x3b, 0xc1, 0xd6, 0xa9, 0x31, 0x68, 0x76, 0x5b, 0x31, 0xeb, 0xdf,
	0xcf, 0x9a, 0x62, 0x70, 0x19, 0x74, 0x32, 0xb7, 0xa5, 0x93, 0x66, 0x49, 0xef, 0x84, 0x99, 0xa9,
	0x5c, 0x84, 0x59, 0xd0, 0x1e, 0x12, 0x41, 0x3e, 0x0e, 0x77, 0x36, 0x13, 0x6f, 0xdc, 0xdb, 0xed,
	0x6c, 0xc4, 0xf7, 0xe8, 0xe4, 0xd3, 0xf5, 0x13, 0x7b, 0x8f, 0x3f, 0xff, 0xf8, 0x75, 0xd5, 0xda,
	0xe9, 0x3d, 0x74, 0xa1, 0xcf, 0x8e, 0x38, 0xb8, 0x11, 0xc7, 0xec, 0xa0, 0xcf, 0x0e, 0xd9, 0xcb,
	0x2b, 0xf6, 0x65, 0xf8, 0x21, 0xdc, 0x1a, 0xdc, 0x3d, 0x4a, 0x0f, 0x0f, 0x58, 0xcb, 0xbc, 0x0e,
	0xf6, 0x87, 0x55, 0x61, 0x50, 0x8b, 0x02, 0xe2, 0x33, 0x28, 0xe1, 0xd3, 0x22, 0x3e, 0xc3, 0x12,
	0x2a, 0x19, 0xfb, 0x47, 0xdb, 0xf8, 0x15, 0x10, 0x8c, 0xc0, 0x8a, 0x70, 0x6f, 0x4c, 0x54, 0xdb,
	0x63, 0xce, 0x2f, 0x61, 0x41, 0xb0, 0x28, 0xd1, 0xb8, 0x78, 0x61, 0x33, 0xe0, 0x7a, 0x19, 0xb1,
	0xef, 0xcb, 0x88, 0xfd, 0x5c, 0x46, 0xec, 0xeb, 0x2a, 0xba, 0xf3, 0x6d, 0x15, 0xb1, 0xeb, 0x55,
	0xc4, 0x3e, 0x46, 0xff, 0x69, 0xe0, 0xcd, 0x1f, 0x8c, 0xda, 0x2e, 0xd8, 0xe7, 0xbf, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x29, 0x43, 0xcb, 0x81, 0xae, 0x02, 0x00, 0x00,
}
