// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tocrawlentry.proto

package domain

import go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/infobloxopen/protoc-gen-gorm/options"
import _ "github.com/gogo/protobuf/types"

import time "time"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

func (this *ToCrawlEntry) Validate() error {
	if this.SubmittedAt != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.SubmittedAt); err != nil {
			return go_proto_validators.FieldError("SubmittedAt", err)
		}
	}
	return nil
}
