// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tocrawlentry.proto

package domain

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/gogo/protobuf/types"

import time "time"

import types "github.com/gogo/protobuf/types"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

type ToCrawlEntry struct {
	ID          uint64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PackagePath string     `protobuf:"bytes,2,opt,name=package_path,json=packagePath,proto3" json:"package_path,omitempty"`
	Reason      string     `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	SubmittedAt *time.Time `protobuf:"bytes,4,opt,name=submitted_at,json=submittedAt,stdtime" json:"submitted_at,omitempty"`
}

func (m *ToCrawlEntry) Reset()                    { *m = ToCrawlEntry{} }
func (m *ToCrawlEntry) String() string            { return proto.CompactTextString(m) }
func (*ToCrawlEntry) ProtoMessage()               {}
func (*ToCrawlEntry) Descriptor() ([]byte, []int) { return fileDescriptorTocrawlentry, []int{0} }

func (m *ToCrawlEntry) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ToCrawlEntry) GetPackagePath() string {
	if m != nil {
		return m.PackagePath
	}
	return ""
}

func (m *ToCrawlEntry) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *ToCrawlEntry) GetSubmittedAt() *time.Time {
	if m != nil {
		return m.SubmittedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*ToCrawlEntry)(nil), "domain.ToCrawlEntry")
}
func (m *ToCrawlEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ToCrawlEntry) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintTocrawlentry(dAtA, i, uint64(m.ID))
	}
	if len(m.PackagePath) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTocrawlentry(dAtA, i, uint64(len(m.PackagePath)))
		i += copy(dAtA[i:], m.PackagePath)
	}
	if len(m.Reason) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintTocrawlentry(dAtA, i, uint64(len(m.Reason)))
		i += copy(dAtA[i:], m.Reason)
	}
	if m.SubmittedAt != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintTocrawlentry(dAtA, i, uint64(types.SizeOfStdTime(*m.SubmittedAt)))
		n1, err := types.StdTimeMarshalTo(*m.SubmittedAt, dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	return i, nil
}

func encodeVarintTocrawlentry(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *ToCrawlEntry) Size() (n int) {
	var l int
	_ = l
	if m.ID != 0 {
		n += 1 + sovTocrawlentry(uint64(m.ID))
	}
	l = len(m.PackagePath)
	if l > 0 {
		n += 1 + l + sovTocrawlentry(uint64(l))
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovTocrawlentry(uint64(l))
	}
	if m.SubmittedAt != nil {
		l = types.SizeOfStdTime(*m.SubmittedAt)
		n += 1 + l + sovTocrawlentry(uint64(l))
	}
	return n
}

func sovTocrawlentry(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozTocrawlentry(x uint64) (n int) {
	return sovTocrawlentry(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ToCrawlEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTocrawlentry
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ToCrawlEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ToCrawlEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTocrawlentry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PackagePath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTocrawlentry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTocrawlentry
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PackagePath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTocrawlentry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTocrawlentry
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubmittedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTocrawlentry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTocrawlentry
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SubmittedAt == nil {
				m.SubmittedAt = new(time.Time)
			}
			if err := types.StdTimeUnmarshal(m.SubmittedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTocrawlentry(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTocrawlentry
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTocrawlentry(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTocrawlentry
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTocrawlentry
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTocrawlentry
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthTocrawlentry
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowTocrawlentry
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipTocrawlentry(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthTocrawlentry = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTocrawlentry   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("tocrawlentry.proto", fileDescriptorTocrawlentry) }

var fileDescriptorTocrawlentry = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8e, 0x31, 0x4e, 0x84, 0x40,
	0x18, 0x85, 0x1d, 0x24, 0x24, 0x0e, 0x14, 0x66, 0x8a, 0x0d, 0xa1, 0x00, 0xb4, 0xa2, 0x71, 0x36,
	0xd1, 0x13, 0xc8, 0x6a, 0x61, 0x67, 0xc8, 0xf6, 0x9b, 0x01, 0xc6, 0x61, 0xe2, 0x0e, 0x3f, 0x81,
	0x9f, 0x18, 0x6f, 0x61, 0xe9, 0x09, 0x3c, 0x8b, 0xa5, 0x27, 0x50, 0x83, 0x17, 0x31, 0x3b, 0xec,
	0x6a, 0xf7, 0xbf, 0xff, 0xbd, 0x97, 0xf7, 0x51, 0x86, 0x50, 0xf5, 0xe2, 0x69, 0x2b, 0x5b, 0xec,
	0x9f, 0x79, 0xd7, 0x03, 0x02, 0xf3, 0x6a, 0x30, 0x42, 0xb7, 0xd1, 0x85, 0xd2, 0xd8, 0x8c, 0x25,
	0xaf, 0xc0, 0x2c, 0x15, 0x28, 0x58, 0x5a, 0xbb, 0x1c, 0x1f, 0xac, 0xb2, 0xc2, 0x5e, 0x73, 0x2d,
	0x4a, 0x14, 0x80, 0xda, 0xca, 0xff, 0x14, 0x6a, 0x23, 0x07, 0x14, 0xa6, 0x9b, 0x03, 0xe7, 0x6f,
	0x84, 0x06, 0x6b, 0x58, 0xed, 0xe6, 0x6e, 0x77, 0x73, 0x6c, 0x41, 0x1d, 0x5d, 0x87, 0x24, 0x25,
	0x99, 0x9b, 0x7b, 0xd3, 0x67, 0xe2, 0xdc, 0xdd, 0x14, 0x8e, 0xae, 0xd9, 0x19, 0x0d, 0x3a, 0x51,
	0x3d, 0x0a, 0x25, 0x37, 0x9d, 0xc0, 0x26, 0x74, 0x52, 0x92, 0x9d, 0x14, 0xfe, 0xfe, 0x77, 0x2f,
	0xb0, 0x61, 0x0b, 0xea, 0xf5, 0x52, 0x0c, 0xd0, 0x86, 0xc7, 0xd6, 0xdc, 0x2b, 0xb6, 0xa2, 0xc1,
	0x30, 0x96, 0x46, 0x23, 0xca, 0x7a, 0x23, 0x30, 0x74, 0x53, 0x92, 0xf9, 0x97, 0x11, 0x9f, 0xd9,
	0xf8, 0x81, 0x8d, 0xaf, 0x0f, 0x6c, 0xb9, 0xfb, 0xf2, 0x95, 0x90, 0xc2, 0xff, 0x6b, 0x5d, 0x63,
	0x7e, 0xfa, 0x3e, 0xc5, 0xe4, 0x63, 0x8a, 0xc9, 0xf7, 0x14, 0x93, 0xd7, 0x9f, 0xf8, 0xa8, 0xf4,
	0x6c, 0xf1, 0xea, 0x37, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x22, 0xe3, 0xd9, 0x2f, 0x01, 0x00, 0x00,
}
